export const ORDER_STATUSES = {
  'IN-PROGRESS': 'IN-PROGRESS',
  'DRIVER-ASSIGNED': 'DRIVER-ASSIGNED',
  'DRIVER-PICKED': 'DRIVER-PICKED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
};

export const USER_TYPES = {
  DRIVER: 'DRIVER',
  CONSUMER: 'CONSUMER',
  ADMIN: 'ADMIN',
};
